import { SettingSchemaDesc } from "@logseq/libs/dist/LSPlugin.user";

export const settings: SettingSchemaDesc[] = [
    {
        key: 'telegramBotToken',
        type: 'string',
        default: '',
        title: 'your telegram bot token',
        description: 'Bot token is the API Key generated by BotFather when you created your bot'
    },
    {
        key: 'telegramChannelName',
        type: 'string',
        default: '',
        title: 'your telegram channel name',
        description: 'Channel name is the handle of your channel (e.g. @my_channel_name)'
    },
    {
        key: 'twitterToken',
        type: 'string',
        default: '',
        title: 'your twitter token',
        description: 'Enter your twitter token for sending tweet'
    }
];